# Generated by Django 4.2.30 on 2026-06-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='revision_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
