# Generated by Django 4.2.30 on 2026-06-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_revision_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
