# Generated by Django 4.2.30 on 2026-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_taken_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_hours',
            field=models.IntegerField(default=1),
        ),
    ]
